version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./tenants:/usr/share/nginx/html/tenants
    depends_on:
      - login-app
      - backend-api

  login-app:
    build: ./login-app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://nginx/api/

  backend-api:
    build: ./backend-api
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge
