server {
    listen 80;
    server_name www.nyraerp.com;

    location / {
        proxy_pass http://login-app:3000;
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend-api:8000;
    }

    location ~ ^/([a-zA-Z0-9_-]+)/ {
        alias /usr/share/nginx/html/tenants/$1/;
        try_files $uri $uri/ /index.html;
    }
}
