server {
    listen 80;

    location /samcarbon/ {
        proxy_pass http://10.0.0.211:5174/samcarbon/;
        proxy_set_header Host $host;
    }

    location /nyra/ {
        proxy_pass http://localhost:5175/nyra;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://10.0.0.211:5173/;
        proxy_set_header Host $host;
    }
}
